CREATE TABLE `ITEMS` (
  `ITEM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ITEM_NAME` varchar(50) NOT NULL,
  `ITEM_PRICE` double(7,2) NOT NULL,
  `ITEM_MIN_QUANTITY` double(3,2) NOT NULL,
  `ITEM_CATEGORY` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1